### ISSUE TITLE
React native paper not working with react native 0.79.1

### ISSUE THREAD

**Issue by Pycode0007** [callstack/react-native-paper#4675]
### Issue

useLatestCallback.default is not a function (it is undefined)

Due to these changes
  // CHANGED - require() syntax
- const ImageBackground = require('react-native/Libraries/Image/ImageBackground');
+ const ImageBackground = require('react-native/Libraries/Image/ImageBackground').default;

// Unchanged - import syntax
import ImageBackground from 'react-native/Libraries/Image/ImageBackground';

// RECOMMENDED - root import
import {ImageBackground} from 'react-native';

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.79.1
| react-native-paper    | 5.13.1

**Comment by nielsq** [comment]
Same

**Comment by helderuni** [comment]
Same

**Comment by lukewalczak** [comment]
@nielsq could you please try install `react-native-paper@0.15.2`? Make sure that `use-latest-callback` in your `node_modules` uses the latest version`0.2.3`?

**Comment by nielsq** [comment]
I still have Issues with my repo
but seems like that error is gone.
@Pycode0007  can you verify?

**Comment by Pycode0007** [comment]
Solved with installing version 0.15.2,

**Comment by nick-carma** [comment]
I don't see version 0.15.2 or 5.15.2 as options for react-native-paper?
