### ISSUE TITLE
Menu._isBrowser returning true on iOS and Android

### ISSUE THREAD

**Issue by isocra** [callstack/react-native-paper#1178]
## Environment

Android and iOS

## Description

I'm trying to use the Menu component, but when I tap the button to show the menu, I get the error: 
```
TypeError: node.querySelector is not a function. (In 'node.querySelector('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')', 'node.querySelector' is undefined)
```
Looking at the code in Menu.js, I can see that `_focusFirstDOMNode` is being called. In fact I tried with a little log statement: 
```javascript
  console.log(`In _focusFirstDOMNode and isBrowser is ${this._isBrowser()}`);
```
And the output of this is `true`, i.e. the code thinks it's in the browser. 

I've tried this on Android and iOS and get the same result. If I change the definition of `_isBrowser` to return false, then everything works.

Can you think of any reason while `'document' in global` might be true? Any work arounds?

## Reproducible Demo

I thought perhaps having a web view in the application (albeit not displayed when I've got the menu showing was maybe the cause, but when I built a minimal test app with a WebView, that worked fine.

**Comment by tasn** [comment]
I'm getting the same, more information: it works fine with 2.15.2 but breaks with 2.16.0.
So a very recent regression.

**Comment by ignaciopicun** [comment]
Getting the same issue here

**Comment by j-alder** [comment]
Also experiencing this issue. Downgrading to 2.15.2 prevented the runtime error, but there are features we need in 2.16.0.

**Comment by tasn** [comment]
Works for me with 3.0.0. Maybe it's also because I updated react-native and a few other things...

**Comment by tavioalves** [comment]
@tasn Hi man, which other things? Which react native version are you using?

**Comment by tasn** [comment]
@tavioalves here's the repo, have a look: https://github.com/etesync/ios
