### ISSUE TITLE
typescript does not compile with react-native 0.71

### ISSUE THREAD

**Issue by julienbachmann** [callstack/react-native-paper#3766]
### Current behaviour
If you try to do a typescript compile with react-native 0.71 and react-native-paper you will have errors like that:
```
tsc --noemit

node_modules/react-native-paper/src/components/Icon.tsx:96:8 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: ImageProps | Readonly<ImageProps>): Image', gave the following error.
    Type '{ accessibilityIgnoresInvertColors: true; role: string; focusable: boolean; accessibilityElementsHidden?: undefined; importantForAccessibility?: undefined; source: any; style: ({ transform: { ...; }[]; } | { ...; })[]; allowFontScaling?: boolean | undefined; } | { ...; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps>'.
      Type '{ accessibilityIgnoresInvertColors: true; role: string; focusable: boolean; accessibilityElementsHidden?: undefined; importantForAccessibility?: undefined; source: any; style: ({ transform: { ...; }[]; } | { ...; })[]; allowFontScaling?: boolean | undefined; }' is not assignable to type 'Readonly<ImageProps>'.
        Types of property 'role' are incompatible.
          Type 'string' is not assignable to type 'Role | undefined'.
  Overload 2 of 2, '(props: ImageProps, context: any): Image', gave the following error.
    Type '{ accessibilityIgnoresInvertColors: true; role: string; focusable: boolean; accessibilityElementsHidden?: undefined; importantForAccessibility?: undefined; source: any; style: ({ transform: { ...; }[]; } | { ...; })[]; allowFontScaling?: boolean | undefined; } | { ...; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Image> & Readonly<ImageProps>'.
      Type '{ accessibilityIgnoresInvertColors: true; role: string; focusable: boolean; accessibilityElementsHidden?: undefined; importantForAccessibility?: undefined; source: any; style: ({ transform: { ...; }[]; } | { ...; })[]; allowFontScaling?: boolean | undefined; }' is not assignable to type 'Readonly<ImageProps>'.
        Types of property 'role' are incompatible.
          Type 'string' is not assignable to type 'Role | undefined'.

96       <Image
          ~~~~~


node_modules/react-native-paper/src/components/MaterialCommunityIcon.tsx:16:19 - error TS2307: Cannot find module 'react-native-vector-icons/MaterialCommunityIcons' or its corresponding type declarations.

16     typeof import('react-native-vector-icons/MaterialCommunityIcons').default
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-paper/src/components/MaterialCommunityIcon.tsx:54:9 - error TS2578: Unused '@ts-expect-error' directive.

54         // @ts-expect-error: Text doesn't support this, but it seems to affect TouchableNativeFeedback
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-native-paper/src/components/TextInput/Adornment/TextInputAdornment.tsx:9:32 - error TS2307: Cannot find module 'src/types' or its corresponding type declarations.

9 import type { ThemeProp } from 'src/types';
                                 ~~~~~~~~~~~

node_modules/react-native-paper/src/components/TextInput/TextInputFlat.tsx:14:32 - error TS2307: Cannot find module 'src/types' or its corresponding type declarations.

14 import type { ThemeProp } from 'src/types';
                                  ~~~~~~~~~~~

node_modules/react-native-paper/src/components/TextInput/TextInputFlat.tsx:363:12 - error TS2322: Type '{ label: TextInputLabelProp | undefined; onLayoutAnimatedText: (args: any) => void; placeholderOpacity: number | Value; labelError: boolean; placeholderStyle: { ...; }; ... 25 more ...; labelLayoutWidth: number; }' is not assignable to type 'LabelProps'.
  Types of property 'contentStyle' are incompatible.
    Type 'StyleProp<ViewStyle>' is not assignable to type 'StyleProp<ViewProps>'.
      Type 'RegisteredStyle<ViewStyle>' is not assignable to type 'StyleProp<ViewProps>'.
        Type 'RegisteredStyle<ViewStyle>' is not assignable to type 'RegisteredStyle<ViewProps>'.
          Type 'RegisteredStyle<ViewStyle>' is not assignable to type '{ __registeredStyleBrand: ViewProps; }'.
            Types of property '__registeredStyleBrand' are incompatible.
              Type 'ViewStyle' has no properties in common with type 'ViewProps'.

363           <InputLabel
               ~~~~~~~~~~

node_modules/react-native-paper/src/components/TextInput/TextInputOutlined.tsx:322:14 - error TS2322: Type '{ labelBackground: ({ labeled, labelLayoutWidth, placeholderStyle, baseLabelTranslateX, topPosition, label, backgroundColor, roundness, labelStyle, maxFontSizeMultiplier, }: LabelBackgroundProps) => (Element | null)[]; maxFontSizeMultiplier: number | null | undefined; label: TextInputLabelProp | undefined; ... 28 mo...' is not assignable to type 'LabelProps'.
  Types of property 'contentStyle' are incompatible.
    Type 'StyleProp<ViewStyle>' is not assignable to type 'StyleProp<ViewProps>'.

322             <InputLabel
                 ~~~~~~~~~~


Found 7 errors in 5 files.

Errors  Files
     1  node_modules/react-native-paper/src/components/Icon.tsx:96
     2  node_modules/react-native-paper/src/components/MaterialCommunityIcon.tsx:16
     1  node_modules/react-native-paper/src/components/TextInput/Adornment/TextInputAdornment.tsx:9
     2  node_modules/react-native-paper/src/components/TextInput/TextInputFlat.tsx:14
     1  node_modules/react-native-paper/src/components/TextInput/TextInputOutlined.tsx:322
make: *** [lint] Error 2
```
### Expected behaviour
compilation should not raise any errors

### How to reproduce?
just launch `tsc --noemit` in a project with react-native 0.71 and react-native-paper

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.71
| react-native-paper    | 5.4.1
| node                            | 16.15.1
| npm or yarn                | 9.2.0
| expo sdk                     | 48.0.7
| typescript.                  | 4.9.4

tsconfig.json is
```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "esModuleInterop": true,
    "module": "ESNext"
  },
  "include": [
    ...myts files
  ],
}
```

**Comment by DimitarNestorov** [comment]
Can you share your TypeScript config?

**Comment by julienbachmann** [comment]
@DimitarNestorov I've just added my tsconfig.json in the bug description

**Comment by DimitarNestorov** [comment]
Can you also let me know the exact versions of Expo and TypeScript that you have installed:
```sh
node -p 'require("expo/package.json").version'
node -p 'require("typescript/package.json").version'
```

**Comment by julienbachmann** [comment]
```
node -p 'require("expo/package.json").version'
48.0.7
node -p 'require("typescript/package.json").version'
4.9.4
```

**Comment by julienbachmann** [comment]
Just to be more clear about the issue. My react-native app is working with react-native 0.71 and react-native-paper. I can build it and it works. 

But if I try to do a `tsc --noemit` to validate my typescript, then I have the error mentioned above.

**Comment by DimitarNestorov** [comment]
To reproduce your errors I added the following in the `include` array in my TypeScript config:
```json
[
    "./node_modules/react-native-paper/**/*.ts",
    "./node_modules/react-native-paper/**/*.tsx"
]
```

tsc should not be compiling TypeScript files under `node_modules`. It will source the relevant types from the definition files (`.d.ts`) that libraries also ship. Please check the `include` value of your configuration.

`npx tsc --listFilesOnly` should show which files TypeScript will compile. That list must contain only `.d.ts` files from `node_modules`.
