### ISSUE TITLE
typescript error caused by `src/utils/forwardRef.tsx` when running `tsc`

### ISSUE THREAD

**Issue by GamerGirlandCo** [callstack/react-native-paper#4609]
### Current behaviour
```
node_modules/react-native-paper/src/utils/forwardRef.tsx:21:14 - error TS2322: Type '<T, P = {}>(render: ForwardRefRenderFunction<T, PropsWithoutRef<P>>) => ForwardRefExoticComponent<PropsWithoutRef<P> & RefAttributes<T>>' is not assignable to type '<T, P = {}>(render: ForwardRefRenderFunction<T, P>) => ForwardRefComponent<T, P>'.
  Types of parameters 'render' and 'render' are incompatible.
    Type 'ForwardRefRenderFunction<T, P>' is not assignable to type 'ForwardRefRenderFunction<T, PropsWithoutRef<P>>'.
      Types of parameters 'props' and 'props' are incompatible.
        Type 'PropsWithoutRef<P>' is not assignable to type 'P'.
          'P' could be instantiated with an arbitrary type which could be unrelated to 'PropsWithoutRef<P>'.
```

### Expected behaviour
type checking should complete without errors

### How to reproduce?
1. clone/download https://snack.expo.dev/@the-tablet/6dd396
2. run `tsc --noEmit` in the project directory

### Preview
N/A

### What have you tried so far?
1. redeclaring typescript module `react-native-paper/src/utils/forwardRef.tsx`
```ts
import 'react-native-paper/src/utils/forwardRef';
declare module 'react-native-paper/src/utils/forwardRef' {
  export declare const forwardRef: <T, P = {}>(
    render: ForwardRefRenderFunction<T, PropsWithoutRef<P>>
  ) => ForwardRefComponent<T, P> = React.forwardRef;
}

```
2. adding `skipLibCheck: true` to tsconfig.json
3. explicitly adding `node_modules/react-native-paper/src` to the `exclude` array in tsconfig.json
4. upgrading react-native-paper to the latest version

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | n/a
| android                        | 35
| react-native                | 0.76.6
| react-native-paper    | 5.13.1
| node                            | 22.12.0
| npm or yarn                | yarn 1.22.22
| expo sdk                     | N/A

**Comment by GamerGirlandCo** [comment]
fwiw, the fix is simple:

```diff
 export const forwardRef: <T, P = {}>(
-  render: ForwardRefRenderFunction<T, P>
+  render: ForwardRefRenderFunction<T, PropsWithoutRef<P>>
 ) => ForwardRefComponent<T, P> = React.forwardRef;
```

**Comment by adorum** [comment]
After upgrading from 5.13.0 to 5.14.4 I am getting typescript error:
```
node_modules/react-native-paper/src/utils/forwardRef.tsx:21:14 - error TS2322: Type '<T, P = {}>(render: ForwardRefRenderFunction<T, P>) => ForwardRefExoticComponent<PropsWithoutRef<P> & RefAttributes<T>>' is not assignable to type '<T, P = {}>(render: ForwardRefRenderFunction<T, PropsWithoutRef<P>>) => ForwardRefComponent<T, P>'.
  Call signature return types 'ForwardRefExoticComponent<PropsWithoutRef<PropsWithoutRef<P>> & RefAttributes<T>>' and 'ForwardRefComponent<T, P>' are incompatible.
    The types of 'defaultProps' are incompatible between these types.
      Type 'Partial<PropsWithoutRef<PropsWithoutRef<P>> & RefAttributes<T>> | undefined' is not assignable to type 'Partial<PropsWithoutRef<P> & RefAttributes<T>> | undefined'.
        Type 'Partial<PropsWithoutRef<PropsWithoutRef<P>> & RefAttributes<T>>' is not assignable to type 'Partial<PropsWithoutRef<P> & RefAttributes<T>>'.
          Type 'keyof PropsWithoutRef<P> | keyof RefAttributes<T>' is not assignable to type 'keyof RefAttributes<T> | keyof PropsWithoutRef<PropsWithoutRef<P>>'.
            Type 'keyof PropsWithoutRef<P>' is not assignable to type 'keyof RefAttributes<T> | keyof PropsWithoutRef<PropsWithoutRef<P>>'.
              Type 'string | number | symbol' is not assignable to type 'keyof RefAttributes<T> | keyof PropsWithoutRef<PropsWithoutRef<P>>'.
                Type 'string' is not assignable to type 'keyof RefAttributes<T> | keyof PropsWithoutRef<PropsWithoutRef<P>>'.
```
